filebeat.prospectors:
- input_type: log
  paths:
    - log4_dir
  document_type: log4
  multiline.pattern: ^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]
  multiline.negate: true
  multiline.match: after
  index: log4
  
- input_type: log
  paths:
    - nginx_dir
  document_type: nginx
  
- input_type: log
  paths:
    - pm2_dir
  document_type: h5
  multiline.pattern: ^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]
  multiline.negate: true
  multiline.match: after
  index: h5
  
output.logstash:
  hosts: ["yourlogstashurl"]
