filebeat.prospectors:
- input_type: log
  paths:
    - /applog/javalog4/log4app.log
  document_type: log4
  multiline.pattern: ^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]
  multiline.negate: true
  multiline.match: after
  index: log4
  
- input_type: log
  paths:
    - /applog/nginx/access.log
  document_type: nginx
  
- input_type: log
  paths:
    - /applog/h5/pm2-app.log
  document_type: h5
  multiline.pattern: ^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]
  multiline.negate: true
  multiline.match: after
  index: h5
  
output.logstash:
  hosts: ["yourlogstashurl"]
